# Parse the ENF Grant Framework Application and return the important parts
# Ted Cahall 25May2022
#
name: Reusable Application Parser
on:
  workflow_call:
    inputs:
      filename:
        required: true
        type: string
    outputs:
      app_email:
        value: ${{ jobs.parse.outputs.app_email }}
      contact_name:
        value: ${{ jobs.parse.outputs.contact_name }}
      project_name:
        value: ${{ jobs.parse.outputs.project_name }}
      team_name:
        value: ${{ jobs.parse.outputs.team_name }}
      total_cost:
        value: ${{ jobs.parse.outputs.total_cost }}
  
jobs:
  parse:
    #if: inputs.filename
    runs-on: ubuntu-latest
    outputs:
      app_email: ${{ steps.grep_appl.outputs.email_addr }}
      contact_name: ${{ steps.grep_appl.outputs.contact_name }}
      project_name: ${{ steps.grep_appl.outputs.project_name }}
      team_name: ${{ steps.grep_appl.outputs.team_name }}
      total_cost: ${{ steps.grep_appl.outputs.total_cost }}
    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }}

      # Parse the application template for the email account
      - name: assign the env from the email name
        id: grep_appl
        run: |
          export APP_EMAIL=`/bin/grep "**Contact Email:**" ${{ inputs.filename }} | cut -d" " -f4`
          echo "::set-output name=email_addr::$APP_EMAIL"
          export CNAME=`/bin/grep "**Contact Name:**" ${{ inputs.filename }} | cut -d" " -f4-8`
          echo "::set-output name=contact_name::$CNAME"
          export PNAME=`/bin/grep "**Project Name:**" ${{ inputs.filename }} | cut -d" " -f4-8`
          echo "::set-output name=project_name::$PNAME"
          export TNAME=`/bin/grep "**Team Name:**" ${{ inputs.filename }} | cut -d" " -f4-8`
          echo "::set-output name=team_name::$TNAME"
          export TCOST=`/bin/grep "**Total Costs:**" ${{ inputs.filename }} | cut -d" " -f4-8`
          echo "::set-output name=total_cost::$TCOST"
